-- Lesson 7: Moving maximum of Scandinavian athletes' medals
-- Type: Exercise </> (100 XP)
-- Engine: PostgreSQL — table summer_medals (Summer Olympic medals). DB built via ../../database/setup.sh
--
-- Instructor fills brief / runnable example / TODO starter here during the lesson.
-- (No solution committed to chapters/.)
