-- Lesson 6: Determining the length of strings
-- Type: Exercise </> (100 XP)
-- Engine: PostgreSQL — Sakila DVD-rental DB (table set: film, actor, rental, payment, customer, …). Built via ../../database/setup.sh
--
-- Instructor fills brief / runnable example / TODO starter here during the lesson.
-- (No solution committed to chapters/.)
