-- ============================================================
-- CAPSTONE — Chapter 4: Window Functions
-- ============================================================
-- Scenario: realistic European Soccer analysis combining every
-- technique from this chapter (OVER, PARTITION BY, sliding windows).
--
-- Instructor writes the full brief + requirements here when the
-- student reaches the end of the chapter. (No solution committed.)
-- ============================================================

-- Write your query below:
